name: "Hello World"
description: "Greet someone and record the time"
outputs:
  result: # id of output
    description: "The result of a event handler"
runs:
  using: "node20"
  main: "dist/index.js"

steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: "20.x"
  - name: Install Dependencies
    run: npm install
  - name: Build
    run: npm run build
  - name: Run Action
    run: node dist/index.js
