name: "Hello World"
description: "Greet someone and record the time"
runs:
  using: "composite"
  steps:
    - run: cd ${{ github.action_path }}
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} --production=true
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} build
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} start
      id: mainHandler
      shell: bash
    outputs:
     result: ${{ steps.mainHandler.outputs.result }}
