name: Bridge workflow
#get log & tags information
on:
  workflow_dispatch:
    inputs:
      eventName:
        description: "name of the handler function"
        required: true
      secretToken:
        description: "PAT token for the repo"
        required: true

jobs:
  handler-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Calling action
        uses: ./ # Uses an action in the root directory
        id: Ubiquity_action
      - name: Print output
        run:
          echo `${{steps.Ubiquity_action.outputs.result}}`
      - name: Trigger repository_dispatch to the repo
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H 'Authorization: Bearer ${{ inputs.secretToken }}' \
          https://api.github.com/repos/wannacfuture/Battleship/dispatches \
          -d '{"event_type":"event-result","client_payload":{"result":"${{steps.Ubiquity_action.outputs.result}}"}}'
